# default rules
homepage:
  url:   /
  param: { module: phony, action: content, page: software }

post_index:
  url:   /post
  param: { module: post, action: index }

post:
  url:  /post/:slug
  param: { module: post, action: show }

tag:
  url:   /tag/:tag
  param: { module: tag, action: show }


content:
  url:  /*
  param: { module: phony, action: content }

