generator:
  class:                  sfPropelAdminGenerator
  param:
    model_class:          User
    theme:                default

    list:
      title:              Users
      display:            [=username, real_name, email, enabled, access_name, created_at]
      actions:
        _create:          { name: New User }

    edit:
      title:              Edit User
      display:
        *Access*:         [username, password, _access, enabled]
        *Info*:           [real_name, email]
      actions:
        _delete:
        _save:            { name: Save }
        _save_and_list:   { name: Done }
